"""Model comparison, validation and MLOps monitoring dashboard."""

import json
from pathlib import Path

import pandas as pd
import streamlit as st

from model_training import TrainingResult, train_and_compare

ROOT = Path(__file__).resolve().parents[1]

st.set_page_config(page_title="Model Metrics & Validation", page_icon="📊", layout="wide")

st.title("📊 MLOps & System Validation")
st.caption("Scientific validation dashboard for the diabetes-risk screening models.")

st.info(
    "Accuracy is shown for completeness, but this project selects models primarily by F1-score, then Recall, then ROC-AUC because false negatives matter in screening contexts."
)

st.markdown(
    """
<div class="clinical-notice">
<b>Institutional Notice:</b> This platform is an educational research framework for chronic-disease prediction and preventative analytics. It is not a certified diagnostic instrument and does not replace licensed medical oversight.
</div>
<br>
<div class="privacy-notice">
<b>Data Privacy Accord:</b> The application is designed to operate statelessly. Biometric inputs and classification outcomes are not written to a persistent patient database by this dashboard.
</div>
""",
    unsafe_allow_html=True,
)

meta_path = ROOT / "model_meta.json"
metrics_path = ROOT / "model_metrics.json"
history_path = ROOT / "history.csv"

if meta_path.exists():
    try:
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        c1, c2, c3 = st.columns(3)
        c1.metric("Selected Model", meta.get("selected_model", "—"))
        c2.metric("Last Trained", meta.get("trained_at_utc", "—"))
        c3.metric("Commit", str(meta.get("commit_sha", "—"))[:7])
    except Exception:
        st.warning("Training metadata could not be read. The live comparison below can still be generated.")
else:
    st.warning("No model_meta.json is available yet. Run the GitHub Actions MLOps retraining workflow to publish the latest metadata.")

@st.cache_resource(show_spinner=False)
def get_training_result() -> TrainingResult:
    return train_and_compare()

with st.spinner("Training baseline and ensemble models with SMOTE and evaluating the held-out test set..."):
    result = get_training_result()

st.subheader("1. Model performance and A/B comparison")
selected_backend = st.selectbox(
    "Select Backend Inference Model",
    ["Logistic Regression", "Random Forest", "XGBoost"],
    index=["Logistic Regression", "Random Forest", "XGBoost"].index(result.best_name),
)

metrics = result.metrics.copy()
for column in ["Accuracy", "Precision", "Recall", "F1-Score", "ROC-AUC"]:
    metrics[column] = metrics[column].map(lambda value: f"{value * 100:.1f}%")

st.dataframe(
    metrics[["Model", "Accuracy", "Precision", "Recall", "F1-Score", "ROC-AUC", "False Negatives", "Threshold"]],
    use_container_width=True,
    hide_index=True,
)

selected_row = result.metrics[result.metrics["Model"] == selected_backend].iloc[0]
c1, c2, c3, c4 = st.columns(4)
c1.metric("Selected", selected_backend)
c2.metric("Accuracy", f"{selected_row['Accuracy'] * 100:.1f}%")
c3.metric("F1-Score", f"{selected_row['F1-Score'] * 100:.1f}%")
c4.metric("Recall", f"{selected_row['Recall'] * 100:.1f}%")

st.caption(
    "The production artifact model.pkl is the model selected by the automated pipeline. The selector above is an evaluation/A-B comparison control and does not silently replace the production artifact."
)

st.subheader("2. Validation artifacts")
asset_cols = st.columns(3)
assets = [
    ("assets/confusion_matrix.png", "Confusion Matrix"),
    ("assets/roc_auc_curve.png", "ROC-AUC Curve"),
    ("assets/shap_importance.png", "Global Feature Importance via XAI"),
]
for column, (relative_path, title) in zip(asset_cols, assets):
    path = ROOT / relative_path
    with column:
        st.markdown(f"**{title}**")
        if path.exists():
            st.image(str(path), use_container_width=True)
        else:
            st.info("This artifact will be generated by the next successful GitHub Actions run.")

best = result.metrics.iloc[0]
st.subheader("3. Confusion-matrix summary")
cm_cols = st.columns(4)
cm_cols[0].metric("True Negatives", int(best["True Negatives"]))
cm_cols[1].metric("False Positives", int(best["False Positives"]))
cm_cols[2].metric("False Negatives", int(best["False Negatives"]))
cm_cols[3].metric("True Positives", int(best["True Positives"]))

st.subheader("4. Training history")
if history_path.exists():
    try:
        history = pd.read_csv(history_path)
        if not history.empty:
            history["trained_at_utc"] = pd.to_datetime(history["trained_at_utc"], errors="coerce")
            available = [c for c in ["Accuracy", "F1-Score", "Recall", "ROC-AUC"] if c in history.columns]
            if available:
                st.line_chart(history.set_index("trained_at_utc")[available])
            st.caption("History records the selected model's held-out metrics after successful training runs.")
        else:
            st.info("Training history is empty. The next successful workflow run will append a record.")
    except Exception as exc:
        st.warning(f"Training history could not be plotted: {exc}")
else:
    st.info("No history.csv is available yet. The automated training workflow will create it after a successful run.")

st.subheader("5. Why F1 → Recall → ROC-AUC?")
st.markdown(
    """
In a screening-oriented model, a **false negative** means a positive case was missed. That can be more consequential than sending a low-risk person for an additional check. The pipeline therefore favors a strong **F1-score**, then **Recall**, then **ROC-AUC** when comparing otherwise similar models. Accuracy remains visible as a supporting metric rather than the only objective.
"""
)

st.subheader("6. Population Drift Monitoring")
st.markdown(
    """
The Pima dataset is a fixed historical cohort, while future users may have different biometric distributions. A production extension would compare incoming feature distributions—especially variables such as **Glucose** and **BMI**—against the training baseline. A deviation of more than **15%** from the baseline mean is defined here as a demonstration alert threshold.

**Current status:** this repository does not persist a live patient stream, so it does **not** claim to have detected real population drift. The section documents the monitoring rule that would be applied once an approved, privacy-preserving data stream exists.
"""
)

st.subheader("7. Algorithmic Fairness & Demographic Subgroup Audit")
st.warning(
    "The Pima Indians Diabetes Dataset contains 768 female participants of Pima Indian heritage. Model performance therefore cannot be assumed to generalize safely to males or to people from other ethnic or demographic populations without external validation."
)

st.subheader("8. Validation notes")
st.markdown(
    """
- **Data balancing:** SMOTE is applied only to the training split, so synthetic observations are not introduced into the held-out evaluation set.
- **Missing measurements:** zero-coded values for glucose, blood pressure, skin thickness, insulin and BMI are treated as missing and median-imputed inside the model pipeline.
- **Baselines:** Logistic Regression, Random Forest and XGBoost are evaluated under the same protocol.
- **Primary selection:** F1-score, then Recall, then ROC-AUC.
- **Reproducibility:** the random seed is fixed at 42 and training metadata records the Git commit SHA.
- **CI quality control:** pytest checks probability bounds and zero-value preprocessing before the retraining job publishes artifacts.
"""
)

st.subheader("9. Automated MLOps log")
commit = "unknown"
trained_at = "unknown"
if meta_path.exists():
    try:
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        commit = str(meta.get("commit_sha", "unknown"))[:7]
        trained_at = meta.get("trained_at_utc", "unknown")
    except Exception:
        pass
st.code(
    f"[SYSTEM INFO] Pipeline retraining managed by GitHub Actions\n"
    f"[METRICS] Optimization target: F1 → Recall → ROC-AUC\n"
    f"[MODEL] Selected: {result.best_name}\n"
    f"[TRAINED] {trained_at}\n"
    f"[COMMIT] {commit}\n"
    f"[DEPLOY] model.pkl + validation artifacts refreshed after CI checks",
    language="text",
)

st.warning(
    "Dataset note: this project uses the Pima Indians Diabetes Dataset (768 samples). Because the dataset is small and population-specific, the application reports actual held-out metrics and does not promise a particular accuracy target."
)
